### ISSUE TITLE
How to change date format in this datepicker?

### ISSUE THREAD

**Issue by ankit18gupta** [goibibo/gWidget#1]
I want to change the date format in this datepicker from mm-dd-yy to yyyy-dd-mm.Is it possible in this datepicker?

**Comment by RUPOJS** [comment]
Hi @ankit18gupta this repo is deprecated, for updated version of datepicker please visit https://github.com/RUPOJS/goDatepicker. There you'll get the selected date in an object named go_cal, you can use that object for all your requirements. Please revert back if you are facing any difficulties or issues.
For more - Please see https://github.com/goibibo/GoWidgets
